# Generated by Django 3.2.6 on 2021-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationprivacy',
            name='permanent_address',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=6),
        ),
        migrations.AddField(
            model_name='informationprivacy',
            name='present_address',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=6),
        ),
        migrations.AlterField(
            model_name='informationprivacy',
            name='phone_privacy',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='hide', max_length=6),
        ),
    ]
