# Generated by Django 3.2.6 on 2021-12-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('registration_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('batch', models.IntegerField()),
                ('phone_Number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('blood_Group', models.CharField(max_length=3)),
                ('present_Address', models.CharField(max_length=70)),
                ('permanent_Address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pro.jpg', upload_to='profile/')),
                ('personal_email', models.EmailField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('registration_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.studentinformation')),
            ],
        ),
    ]
