# Generated by Django 4.0 on 2021-12-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_studentinformation_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='registration_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
