# Generated by Django 4.0 on 2021-12-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_studentinformation_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='blood_Group',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
