# Generated by Django 4.0 on 2021-12-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_alter_studentinformation_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='blood_Group',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
