# Generated by Django 4.0 on 2021-12-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_alter_studentinformation_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedinformation',
            name='company',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='extendedinformation',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendedinformation',
            name='position',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='facebook',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='github',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='linkedin',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='personal_email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
