# Generated by Django 4.0 on 2021-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_extendedinformation_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedinformation',
            name='company',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='facebook',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='github',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='image',
            field=models.ImageField(default='pro.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='linkedin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='personal_email',
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendedinformation',
            name='position',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
