# Generated by Django 4.0 on 2021-12-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0009_extendedinformation_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('registration_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.studentinformation')),
            ],
        ),
    ]
