# Generated by Django 4.0 on 2021-12-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_auth', '0002_otp_is_verified_alter_otp_otp_alter_otp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='OTP',
            new_name='auth_otp',
        ),
    ]
