# Generated by Django 3.2.6 on 2021-12-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_donated', models.DateField(blank=True, verbose_name=['%m/%d/%y'])),
                ('want_donate', models.CharField(max_length=10)),
                ('registration_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.studentinformation')),
            ],
        ),
    ]
